from typing import Protocol, Sequence

class PDFExtractor(Protocol):
    def extract_text_from_page(self, page) -> str: ...
    def process_pdf(self, file_path: str) -> list[dict]: ...
    def save_to_txt(self, pages_data: list[dict], output_path: str): ...
    @staticmethod
    def chunk_text(text: str, chunk_size: int = 200) -> list[str]: ...