from typing import Protocol

class SummaryGenerator(Protocol):
    @staticmethod
    def chunk_text(text: str, chunk_size: int = 200) -> list[str]: ...
    def summarize_chunk(self, text_chunk: str) -> str: ...
    def summarize(self, text: str, chunk_size: int = 200) -> str: ...